// <auto-generated />
using System;
using MechKeyboardBase.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MechKeyboardBase.Infrastructure.Migrations
{
    [DbContext(typeof(MechKeyboardBaseDbContext))]
    [Migration("20190916062856_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MechKeyboardBase.Core.Entities.Keyboard", b =>
                {
                    b.Property<int>("KeyboardId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Case");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("KeyboardName");

                    b.Property<string>("Keycaps");

                    b.Property<string>("PCB");

                    b.Property<string>("Plate");

                    b.Property<string>("Switch");

                    b.Property<string>("Username");

                    b.Property<string>("VideoUrl");

                    b.HasKey("KeyboardId");

                    b.ToTable("Keyboard");
                });

            modelBuilder.Entity("MechKeyboardBase.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Role");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
