// <auto-generated />
using System;
using MechKeyboardBase.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MechKeyboardBase.Infrastructure.Migrations
{
    [DbContext(typeof(MechKeyboardBaseDbContext))]
    partial class MechKeyboardBaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MechKeyboardBase.Core.Entities.Keyboard", b =>
                {
                    b.Property<int>("KeyboardId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DetailsId");

                    b.Property<string>("Inspiration");

                    b.Property<string>("KeyboardName");

                    b.Property<string>("Username");

                    b.HasKey("KeyboardId");

                    b.HasIndex("DetailsId");

                    b.ToTable("Keyboard");
                });

            modelBuilder.Entity("MechKeyboardBase.Core.Entities.KeyboardDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Case");

                    b.Property<string>("Keycaps");

                    b.Property<string>("PCB");

                    b.Property<string>("Plate");

                    b.Property<string>("Switch");

                    b.HasKey("Id");

                    b.ToTable("KeyboardDetails");
                });

            modelBuilder.Entity("MechKeyboardBase.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Role");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MechKeyboardBase.Core.Entities.Keyboard", b =>
                {
                    b.HasOne("MechKeyboardBase.Core.Entities.KeyboardDetails", "Details")
                        .WithMany()
                        .HasForeignKey("DetailsId");
                });
#pragma warning restore 612, 618
        }
    }
}
