// <auto-generated />
using System;
using MechKeyboardBase.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MechKeyboardBase.Web.Migrations
{
    [DbContext(typeof(MechKeyboardBaseDbContext))]
    [Migration("20190829101551_initialdb")]
    partial class initialdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MechKeyboardBase.Web.Models.Keyboard", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Inspiration");

                    b.Property<int?>("KeyboardDetailsId");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("KeyboardDetailsId");

                    b.ToTable("Keyboard");
                });

            modelBuilder.Entity("MechKeyboardBase.Web.Models.KeyboardBuild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Case");

                    b.Property<string>("KeyCaps");

                    b.Property<string>("PCB");

                    b.Property<string>("Plate");

                    b.Property<string>("Switch");

                    b.HasKey("Id");

                    b.ToTable("KeyboardBuild");
                });

            modelBuilder.Entity("MechKeyboardBase.Web.Models.Keyboard", b =>
                {
                    b.HasOne("MechKeyboardBase.Web.Models.KeyboardBuild", "KeyboardDetails")
                        .WithMany()
                        .HasForeignKey("KeyboardDetailsId");
                });
#pragma warning restore 612, 618
        }
    }
}
